# Generated by Django 4.0.4 on 2022-05-30 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familiares', '0003_alter_familiares_apellido_alter_familiares_dni_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiares',
            name='dni',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
